### ISSUE TITLE
Choice 29 Get test token got bug

### ISSUE THREAD

**Issue by THEGOODBALL** [VatosV2/Nexus-MultiTool#13]
![Screenshot 2024-08-13 200026](https://github.com/user-attachments/assets/e5b15024-765e-4bb1-9618-da6fdaea5146)
Bug error code
        GetHandleVerifier [0x009F8923+23283]
        (No symbol) [0x009BE934]
        (No symbol) [0x008F0733]
        (No symbol) [0x0093326F]
        (No symbol) [0x009334AB]
        (No symbol) [0x0096EE42]
        (No symbol) [0x00954464]
        (No symbol) [0x0096CB8D]
        (No symbol) [0x009541B6]
        (No symbol) [0x00928017]
        (No symbol) [0x0092890D]
        GetHandleVerifier [0x00AEA5E3+1013683]
        GetHandleVerifier [0x00AF3E3C+1052684]
        GetHandleVerifier [0x00AED4A4+1025652]
        GetHandleVerifier [0x00A1EA2B+179195]
        (No symbol) [0x009C6833]
        (No symbol) [0x009C3198]
        (No symbol) [0x009C3337]
        (No symbol) [0x009BB4BE]
        BaseThreadInitThunk [0x75EBFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77BB80CE+286]
        RtlGetAppContainerNamedObjectPath [0x77BB809E+238]

faf

**Comment by ndyjan1337** [comment]
how did that happen?

**Comment by THEGOODBALL** [comment]
> how did that happen?

yea

**Comment by VatosV2** [comment]
Will get fixed discord updated some tags in the html of register
