### ISSUE TITLE
they nuked me. dont download.

### ISSUE THREAD

**Issue by giannisgeorg2** [VatosV2/Nexus-MultiTool#2]
Vatos and his  tools  are legit, there was a misunderstanding with another creator who copied his tools and converted them into rats.

**Comment by monkeyrizz** [comment]
dayum bro im sorry to hear that man :/

**Comment by giannisgeorg2** [comment]
> dayum bro im sorry to hear that man :/
 its all good bro i just want to save more people from downloading  this

**Comment by VatosV2** [comment]
bro that was not us lil bro 😭 there are 1:1 copys of our tool but not us. discord.gg/nexustools come and we talk
